apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-web-app
  namespace: azure-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-web-app
  template:
    metadata:
      labels:
        app: azure-web-app
    spec:
      imagePullSecrets:
      - name: acr-pull
      containers:
      - name: azure-web-app
        image: lordloks/azure-web-app:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: azure-web-app-service
  namespace: azure-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: azure-web-app 