apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-web-app
  template:
    metadata:
      labels:
        app: azure-web-app
    spec:
      containers:
      - name: azure-web-app
        image: lordloks/azure-web-app:latest
        ports:
        - containerPort: 80
      # --- Вот здесь вы указываете ноду для деплоя ---
      nodeSelector:
        disktype: ssd
      # -----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: azure-web-app-service
  namespace: azure-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: azure-web-app 