name: Deploy to AKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: kolyaacr
  AKS_CLUSTER_NAME: atom-demo-cluster
  RESOURCE_GROUP: atom-demo2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push container image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/azure-web-app:${{ github.sha }} .
        docker push ${{ env.ACR_NAME }}.azurecr.io/azure-web-app:${{ github.sha }}

    - name: Get AKS credentials
      uses: azure/aks-set-context@v2
      with:
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}

    - name: Deploy to AKS
      run: |
        sed -i 's|image: kolyaacr.azurecr.io/azure-web-app:latest|image: kolyaacr.azurecr.io/azure-web-app:${{ github.sha }}|' deployment.yaml
        kubectl apply -f deployment.yaml 