name: CI/CD to AKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: kolyaacr.azurecr.io
  IMAGE_NAME: azure-web-app
  NAMESPACE: default

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Basic tests
      run: |
        test -f index.html
        grep -qi "<html" index.html

    - name: Docker login to ACR
      run: echo "$ACR_PASSWORD" | docker login ${REGISTRY} -u "$ACR_USERNAME" --password-stdin
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

    - name: Build image
      run: |
        docker build -t ${REGISTRY}/${IMAGE_NAME}:latest -t ${REGISTRY}/${IMAGE_NAME}:${{ github.sha }} .

    - name: Push image
      run: |
        docker push ${REGISTRY}/${IMAGE_NAME}:latest
        docker push ${REGISTRY}/${IMAGE_NAME}:${{ github.sha }}

    - name: Configure kubectl context from secret
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBE_CONFIG" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    - name: Update deployment image (rolling update)
      run: |
        set -e
        kubectl -n ${NAMESPACE} set image deployment/azure-web-app azure-web-app=${REGISTRY}/${IMAGE_NAME}:${{ github.sha }} || true
        kubectl -n ${NAMESPACE} rollout status deployment/azure-web-app --timeout=120s || true

    - name: Fallback apply manifests (first-time deploy)
      run: |
        sed -i "s|image: .*|image: ${REGISTRY}/${IMAGE_NAME}:${{ github.sha }}|" deployment.yaml
        kubectl apply -f deployment.yaml
        kubectl -n ${NAMESPACE} rollout status deployment/azure-web-app --timeout=180s 
